# Generated by Django 5.2 on 2025-06-21 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_likepost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likepost',
            old_name='psot_id',
            new_name='post_id',
        ),
    ]
